services:
  app:
    build:
      context: ./
      dockerfile: Containerfile
    image: test
    environment:
      - DATABASE_URI=mongodb://root:root@slowers-mongodb
    ports:
      - 5001:5001
    container_name: test

  db:
    image: docker.io/mongo:7.0.0
    ports:
      - 27017:27017
    container_name: test_db
